Repository piitaya/lovelace-mushroom, pull requests merged in 2022-02, with the labels that each got.

#63 feat(person): allow user to hide name
  .hass_dev/views/person-view.yaml
  docs/cards/person.md
  src/cards/person-card/person-card-config.ts
  src/cards/person-card/person-card-editor.ts
  src/cards/person-card/person-card.ts
  src/translations/en.json
  src/translations/fr.json
Labels: enhancement

#66 fix(chip): vertically center weather icon and make icon-only chips round
  src/shared/chip.ts
Labels: bug

#65 feat(person): use zone icon when available
  .hass_dev/configuration.yaml
  src/cards/person-card/person-card.ts
  src/cards/person-card/utils.ts
Labels: enhancement

#68 feat(person): add info color when person in zone
  src/cards/person-card/person-card.ts
  src/cards/person-card/utils.ts
  src/utils/colors.ts
Labels: enhancement

#46 feat: add theme usage
  README.md
  src/cards/chips-card/chips-card.ts
  src/shared/button.ts
  src/shared/chip.ts
  src/shared/shape-avatar.ts
  src/shared/shape-icon.ts
  src/shared/slider.ts
  src/utils/card-styles.ts
  src/utils/chip-styles.ts
  themes/mushroom.yaml
Labels: enhancement

#64 feat(icon): allow user to hide icon in template and entity cards
  .hass_dev/views/entity-view.yaml
  .hass_dev/views/template-view.yaml
  docs/cards/entity.md
  docs/cards/template.md
  src/cards/entity-card/entity-card-config.ts
  src/cards/entity-card/entity-card-editor.ts
  src/cards/entity-card/entity-card.ts
  src/cards/template-card/template-card-editor.ts
  src/cards/template-card/template-card.ts
  src/translations/en.json
  src/translations/fr.json
Labels: enhancement

#48 feat(light): handle color
  .hass_dev/lovelace-mushroom-showcase.yaml
  .hass_dev/views/light-view.yaml
  .prettierrc.js
  docs/cards/light.md
  package-lock.json
  package.json
  src/cards/light-card/controls/light-brightness-control.ts
  src/cards/light-card/controls/light-color-control.ts
  src/cards/light-card/controls/light-color-temp-control.ts
  src/cards/light-card/light-card-config.ts
  src/cards/light-card/light-card-editor.ts
  src/cards/light-card/light-card.ts
  src/cards/light-card/utils.ts
  src/shared/shape-icon.ts
  src/shared/slider.ts
  src/translations/en.json
  src/translations/fr.json
Labels: enhancement

#131 feat(chips): add alarm control panel chip
  .hass_dev/configuration.yaml
  .hass_dev/views/chips-view.yaml
  docs/cards/chips.md
  docs/images/chip-alarm-control-panel-dark.png
  docs/images/chip-alarm-control-panel-light.png
  src/cards/alarm-control-panel-card/alarm-control-panel-card.ts
  src/cards/alarm-control-panel-card/utils.ts
  src/cards/chips-card/chips-card-chips-editor.ts
  src/cards/chips-card/chips/alarm-control-panel-chip-editor.ts
  src/cards/chips-card/chips/alarm-control-panel-chip.ts
  src/cards/chips-card/chips/conditional-chip-editor.ts
  src/cards/chips-card/chips/index.ts
  src/shared/chip.ts
  src/shared/shape-icon.ts
  src/translations/en.json
  src/translations/fr.json
  src/utils/entity-styles.ts
  src/utils/lovelace/chip/types.ts
Labels: enhancement

#132 feat(layout): add default, horizontal and vertical layout for all cards
  .hass_dev/views/alarm-control-panel-view.yaml
  .hass_dev/views/cover-view.yaml
  .hass_dev/views/entity-view.yaml
  .hass_dev/views/fan-view.yaml
  .hass_dev/views/light-view.yaml
  .hass_dev/views/person-view.yaml
  .hass_dev/views/template-view.yaml
  docs/cards/alarm.md
  docs/cards/cover.md
  docs/cards/entity.md
  docs/cards/fan.md
  docs/cards/light.md
  docs/cards/person.md
  docs/cards/template.md
  src/cards/alarm-control-panel-card/alarm-control-panel-card-config.ts
  src/cards/alarm-control-panel-card/alarm-control-panel-card-editor.ts
  src/cards/alarm-control-panel-card/alarm-control-panel-card.ts
  src/cards/cover-card/controls/cover-buttons-control.ts
  src/cards/cover-card/cover-card-config.ts
  src/cards/cover-card/cover-card-editor.ts
  src/cards/cover-card/cover-card.ts
  src/cards/entity-card/entity-card-config.ts
  src/cards/entity-card/entity-card-editor.ts
  src/cards/entity-card/entity-card.ts
  src/cards/fan-card/fan-card-config.ts
  src/cards/fan-card/fan-card-editor.ts
  src/cards/fan-card/fan-card.ts
  src/cards/light-card/light-card-config.ts
  src/cards/light-card/light-card-editor.ts
  src/cards/light-card/light-card.ts
  src/cards/person-card/person-card-config.ts
  src/cards/person-card/person-card-editor.ts
  src/cards/person-card/person-card.ts
  src/cards/template-card/template-card-config.ts
  src/cards/template-card/template-card-editor.ts
  src/cards/template-card/template-card.ts
  src/shared/card.ts
  src/shared/chip.ts
  src/shared/editor/layout-picker.ts
  src/shared/state-item.ts
  src/translations/en.json
  src/translations/fr.json
  src/utils/card-styles.ts
  src/utils/info.ts
  src/utils/layout.ts
  src/utils/lovelace/element-editor.ts
Labels: enhancement

#140 fix(light): only show brightness controls if light support it
  .hass_dev/configuration.yaml
  src/cards/light-card/light-card.ts
  src/cards/light-card/utils.ts
Labels: bug

#139 fix(chips): fix support for hold and double tap action for template chip
  src/cards/chips-card/chips/template-chip.ts
Labels: bug

#130 add portuguese brazilian language support
  src/localize.ts
  src/translations/pt-BR.json
Labels: translations

#141 add simplified chinese support.
  src/localize.ts
  src/translations/zh-Hans.json
Labels: translations

#147 fix: use same entity icons rules as home assistant frontend
  src/cards/alarm-control-panel-card/alarm-control-panel-card-editor.ts
  src/cards/alarm-control-panel-card/alarm-control-panel-card.ts
  src/cards/alarm-control-panel-card/const.ts
  src/cards/alarm-control-panel-card/utils.ts
  src/cards/chips-card/chips/alarm-control-panel-chip-editor.ts
  src/cards/chips-card/chips/alarm-control-panel-chip.ts
  src/cards/chips-card/chips/entity-chip-editor.ts
  src/cards/chips-card/chips/entity-chip.ts
  src/cards/chips-card/chips/light-chip-editor.ts
  src/cards/chips-card/chips/light-chip.ts
  src/cards/cover-card/controls/cover-buttons-control.ts
  src/cards/cover-card/cover-card-editor.ts
  src/cards/cover-card/cover-card.ts
  src/cards/entity-card/entity-card-editor.ts
  src/cards/entity-card/entity-card.ts
  src/cards/fan-card/fan-card-editor.ts
  src/cards/fan-card/fan-card.ts
  src/cards/light-card/light-card-editor.ts
  src/cards/light-card/light-card.ts
  src/cards/person-card/person-card-editor.ts
  src/cards/person-card/person-card.ts
  src/utils/icons/alarm-panel-icon.ts
  src/utils/icons/binary-sensor-icon.ts
  src/utils/icons/cover-icon.ts
  src/utils/icons/domain-icon.ts
  src/utils/icons/sensor-icon.ts
  src/utils/icons/state-icon.ts
Labels: bug

#157 fix(person): fix hold action selector in editor
  src/cards/person-card/person-card-editor.ts
Labels: bug
