Repository piitaya/lovelace-mushroom, pull requests merged in 2022-05, with the labels that each got.

#428 fix(chips): fix flickering in template chips
  src/cards/chips-card/chips-card.ts
  src/utils/base-element.ts
Labels: bug

#440 fix(cover): fix cover for unavailable/unknown cover
  src/cards/cover-card/utils.ts
Labels: bug

#430 fix(cards): use entity_picture_local when necessary
  src/cards/chips-card/chips/entity-chip.ts
  src/cards/entity-card/entity-card.ts
  src/cards/media-player-card/media-player-card.ts
  src/cards/person-card/person-card.ts
  src/cards/update-card/update-card.ts
  src/ha/data/entity.ts
Labels: bug

#374 feat(media-player): show volume next to state when not unavailable/unknown/off
  src/cards/media-player-card/controls/media-player-volume-control.ts
  src/cards/media-player-card/media-player-card.ts
Labels: enhancement

#452 feat(media-player): add option to display volume level
  .hass_dev/views/media-player-view.yaml
  docs/cards/media-player.md
  src/cards/media-player-card/media-player-card-config.ts
  src/cards/media-player-card/media-player-card-editor.ts
  src/cards/media-player-card/media-player-card.ts
  src/translations/en.json
  src/translations/fr.json
Labels: enhancement

#308 feat(graph): support of graph card
  .hass_dev/lovelace-mushroom-showcase.yaml
  .hass_dev/views/graph-view.yaml
  docs/cards/graph.md
  docs/images/graph-dark.png
  docs/images/graph-light.png
  src/cards/graph-card/const.ts
  src/cards/graph-card/graph-card-config.ts
  src/cards/graph-card/graph-card-editor.ts
  src/cards/graph-card/graph-card.ts
  src/cards/graph-card/utils.ts
  src/ha/data/graph.ts
  src/ha/data/history.ts
  src/mushroom.ts
  src/shared/graph/coordinates.ts
  src/shared/graph/graph-base.ts
  src/translations/en.json
  src/translations/fr.json
  src/utils/lovelace/graph/utils.ts
Labels: enhancement

#469 Fix/scroll actions
  src/cards/cover-card/cover-card-editor.ts
  src/utils/card-styles.ts
Labels: bug

#470 Update README to reflect recent UI changes in HA
  README.md
Labels: documentation

#494 fix(picture): fix entity picture on cast devices
  src/cards/chips-card/chips/entity-chip.ts
  src/cards/entity-card/entity-card.ts
  src/cards/media-player-card/media-player-card.ts
  src/cards/person-card/person-card.ts
  src/cards/update-card/update-card.ts
Labels: bug

#484 Add Spanish translation
  src/localize.ts
  src/translations/es.json
Labels: translations

#495 fix(person): fix state not displayed on cast devices
  src/cards/chips-card/chips/entity-chip.ts
  src/cards/person-card/person-card.ts
Labels: bug

#482 fix: missing ha-card
  src/cards/chips-card/chips-card.ts
Labels: bug

#499 Revert "fix: missing ha-card"
  src/cards/chips-card/chips-card.ts
Labels: bug

#502 feat(chip): improve stack in card support
  src/cards/chips-card/chips-card.ts
  src/shared/chip.ts
Labels: enhancement

#503 fix(button): ignore button ratio if fill mode for button group
  src/shared/button-group.ts
Labels: bug

#501 added 'Show Volume Level' and 'Collapse Controls translations'
  src/translations/nl.json
Labels: translations

#496 feat(theme): add card text line height variable
  src/shared/state-info.ts
  src/utils/theme.ts
Labels: enhancement

#509 Add Hebrew translation
  src/localize.ts
  src/translations/he.json
Labels: translations

#512 fix(chip): restore ha-card element on chip for better styling
  src/shared/chip.ts
Labels: bug

#516 split configuration into packages
  .gitignore
  .hass_dev/configuration.yaml
  .hass_dev/packages/alarm_control_panel.yaml
  .hass_dev/packages/demo.yaml
  .hass_dev/packages/light.yaml
  .hass_dev/packages/person.yaml
Labels: tech

#521 feat(slider): add animation and step support to slider
  src/cards/fan-card/controls/fan-percentage-control.ts
  src/cards/fan-card/fan-card.ts
  src/cards/fan-card/utils.ts
  src/shared/slider.ts
Labels: enhancement

#523 refactor(config): share config between cards
  src/cards/alarm-control-panel-card/alarm-control-panel-card-config.ts
  src/cards/chips-card/chips-card-editor.ts
  src/cards/cover-card/cover-card-config.ts
  src/cards/entity-card/entity-card-config.ts
  src/cards/fan-card/fan-card-config.ts
  src/cards/humidifier-card/humidifier-card-config.ts
  src/cards/light-card/light-card-config.ts
  src/cards/lock-card/lock-card-config.ts
  src/cards/media-player-card/media-player-card-config.ts
  src/cards/person-card/person-card-config.ts
  src/cards/template-card/template-card-config.ts
  src/cards/title-card/title-card-config.ts
  src/cards/update-card/update-card-config.ts
  src/cards/vacuum-card/vacuum-card-config.ts
  src/shared/config/actions-config.ts
  src/shared/config/entity-config.ts
  src/shared/config/infos-config.ts
  src/shared/config/layout-config.ts
  src/shared/config/lovelace-card-config.ts
  src/utils/editor-styles.ts
Labels: tech
