Repository piitaya/lovelace-mushroom, pull requests merged in 2022-04, with the labels that each got.

#220 fix(alarm): allow to disarm when alarm is pending
  src/cards/alarm-control-panel-card/utils.ts
Labels: bug

#219 feat(slider): allow user to customize the slider threshold with theme
  src/shared/slider.ts
  src/utils/card-styles.ts
Labels: enhancement

#221 add Italian Translation
  src/localize.ts
  src/translations/it.json
Labels: translations

#225 fix(translation): italian translation
  src/translations/it.json
Labels: translations

#256 Feature/vacuum card
  .gitattributes
  .hass_dev/lovelace-mushroom-showcase.yaml
  .hass_dev/views/vacuum-view.yaml
  README.md
  docs/cards/vacuum.md
  docs/images/vacuum-dark.png
  docs/images/vacuum-light.png
  package-lock.json
  package.json
  src/cards/vacuum-card/const.ts
  src/cards/vacuum-card/controls/vacuum-clean-spot-control.ts
  src/cards/vacuum-card/controls/vacuum-locate-control.ts
  src/cards/vacuum-card/controls/vacuum-return-home-control.ts
  src/cards/vacuum-card/controls/vacuum-start-pause-control.ts
  src/cards/vacuum-card/controls/vacuum-stop-control.ts
  src/cards/vacuum-card/utils.ts
  src/cards/vacuum-card/vacuum-card-config.ts
  src/cards/vacuum-card/vacuum-card-editor.ts
  src/cards/vacuum-card/vacuum-card.ts
  src/mushroom.ts
  src/translations/de.json
  src/translations/el.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/it.json
  src/translations/nl.json
  src/translations/pt-BR.json
  src/translations/sv.json
  src/translations/zh-Hans.json
  src/translations/zh-Hant.json
  src/utils/colors.ts
  src/utils/icons/vacuum-icon.ts
Labels: enhancement

#260 chore: add entity helpers
  src/cards/alarm-control-panel-card/alarm-control-panel-card-editor.ts
  src/cards/alarm-control-panel-card/alarm-control-panel-card.ts
  src/cards/chips-card/chips/alarm-control-panel-chip.ts
  src/cards/chips-card/chips/entity-chip.ts
  src/cards/chips-card/chips/light-chip.ts
  src/cards/chips-card/chips/weather-chip.ts
  src/cards/cover-card/controls/cover-buttons-control.ts
  src/cards/cover-card/controls/cover-position-control.ts
  src/cards/cover-card/cover-card.ts
  src/cards/cover-card/utils.ts
  src/cards/entity-card/entity-card.ts
  src/cards/fan-card/controls/fan-oscillate-control.ts
  src/cards/fan-card/controls/fan-percentage-control.ts
  src/cards/fan-card/fan-card.ts
  src/cards/light-card/controls/light-brightness-control.ts
  src/cards/light-card/controls/light-color-control.ts
  src/cards/light-card/controls/light-color-temp-control.ts
  src/cards/light-card/light-card.ts
  src/cards/light-card/utils.ts
  src/cards/person-card/person-card.ts
  src/cards/update-card/controls/update-buttons-control.ts
  src/cards/update-card/update-card.ts
  src/cards/update-card/utils.ts
  src/cards/vacuum-card/const.ts
  src/cards/vacuum-card/utils.ts
  src/cards/vacuum-card/vacuum-card.ts
  src/ha/common/const.ts
  src/ha/common/entity/compute-domain.ts
  src/ha/common/entity/compute-state-display.ts
  src/ha/common/entity/compute-state-domain.ts
  src/ha/common/entity/supports-feature.ts
  src/ha/data/climate.ts
  src/ha/data/cover.ts
  src/ha/data/entity.ts
  src/ha/data/fan.ts
  src/ha/data/light.ts
  src/ha/data/update.ts
  src/ha/data/vacuum.ts
  src/shared/button-group.ts
  src/utils/compute-state-display.ts
  src/utils/icons/domain-icon.ts
  src/utils/icons/vacuum-icon.ts
  src/utils/info.ts
Labels: tech

#274 Improve Dutch translations
  src/translations/nl.json
Labels: translations

#307 fix: do not consider unavailable if entity state in unknown
  src/cards/alarm-control-panel-card/alarm-control-panel-card.ts
  src/cards/alarm-control-panel-card/utils.ts
  src/cards/cover-card/cover-card.ts
  src/cards/light-card/light-card.ts
  src/cards/person-card/person-card.ts
  src/cards/person-card/utils.ts
  src/ha/data/entity.ts
Labels: bug

#270 feat(media_player): add support of media player
  .hass_dev/lovelace-mushroom-showcase.yaml
  .hass_dev/views/media-player-view.yaml
  README.md
  docs/cards/media-player.md
  docs/images/media-player-dark.png
  docs/images/media-player-light.png
  src/cards/media-player-card/const.ts
  src/cards/media-player-card/controls/media-player-buttons-control.ts
  src/cards/media-player-card/controls/media-player-volume-control.ts
  src/cards/media-player-card/media-player-card-config.ts
  src/cards/media-player-card/media-player-card-editor.ts
  src/cards/media-player-card/media-player-card.ts
  src/cards/media-player-card/utils.ts
  src/ha/data/media-player.ts
  src/mushroom.ts
  src/translations/en.json
  src/translations/fr.json
  src/utils/colors.ts
Labels: enhancement

#310 feat(rtl): add rtl support
  src/cards/alarm-control-panel-card/alarm-control-panel-card.ts
  src/cards/chips-card/chips-card.ts
  src/cards/chips-card/chips/action-chip.ts
  src/cards/chips-card/chips/alarm-control-panel-chip.ts
  src/cards/chips-card/chips/back-chip.ts
  src/cards/chips-card/chips/conditional-chip-editor.ts
  src/cards/chips-card/chips/entity-chip.ts
  src/cards/chips-card/chips/light-chip.ts
  src/cards/chips-card/chips/menu-chip.ts
  src/cards/chips-card/chips/template-chip.ts
  src/cards/chips-card/chips/weather-chip.ts
  src/cards/cover-card/controls/cover-buttons-control.ts
  src/cards/cover-card/cover-card.ts
  src/cards/entity-card/entity-card.ts
  src/cards/fan-card/fan-card.ts
  src/cards/light-card/light-card.ts
  src/cards/person-card/person-card.ts
  src/cards/template-card/template-card.ts
  src/cards/update-card/controls/update-buttons-control.ts
  src/cards/update-card/update-card.ts
  src/cards/vacuum-card/controls/vacuum-commands-control.ts
  src/cards/vacuum-card/vacuum-card.ts
  src/shared/button-group.ts
  src/shared/card.ts
  src/shared/chip.ts
  src/shared/slider.ts
  src/shared/state-item.ts
  src/utils/card-styles.ts
Labels: bug

#311 fix(slider): fix slider for cover and fan when disable
  src/cards/cover-card/controls/cover-position-control.ts
  src/cards/fan-card/controls/fan-percentage-control.ts
Labels: bug

#312 feat(media-player): improve media player
  .hass_dev/views/media-player-view.yaml
  src/cards/media-player-card/controls/media-player-buttons-control.ts
  src/cards/media-player-card/controls/media-player-commands-control.ts
  src/cards/media-player-card/controls/media-player-volume-control.ts
  src/cards/media-player-card/media-player-card-config.ts
  src/cards/media-player-card/media-player-card-editor.ts
  src/cards/media-player-card/media-player-card.ts
  src/cards/media-player-card/utils.ts
  src/cards/vacuum-card/vacuum-card-config.ts
  src/ha/data/entity.ts
  src/ha/data/media-player.ts
  src/translations/en.json
  src/translations/fr.json
  src/utils/form/ha-selector.ts
Labels: enhancement

#316 feat(lock): add lock support
  .hass_dev/lovelace-mushroom-showcase.yaml
  .hass_dev/views/lock-view.yaml
  docs/cards/lock.md
  docs/images/lock-dark.png
  docs/images/lock-light.png
  src/cards/lock-card/const.ts
  src/cards/lock-card/controls/lock-buttons-control.ts
  src/cards/lock-card/lock-card-config.ts
  src/cards/lock-card/lock-card-editor.ts
  src/cards/lock-card/lock-card.ts
  src/cards/lock-card/utils.ts
  src/cards/vacuum-card/controls/vacuum-commands-control.ts
  src/ha/data/lock.ts
  src/mushroom.ts
  src/utils/colors.ts
Labels: enhancement

#322 Update zh-Hant.json
  src/translations/zh-Hant.json
Labels: translations

#340 fix(layout): fix rtl icon alignment in vertical layout
  src/shared/state-item.ts
Labels: bug

#372 Tiny Bugfix + Updated Italian translation
  src/cards/title-card/title-card.ts
  src/translations/it.json
  src/utils/icons/cover-icon.ts
Labels: bug, translations

#375 fix(alarm): fix alarm panel display for some layouts
  src/cards/alarm-control-panel-card/alarm-control-panel-card.ts
  src/shared/card.ts
Labels: bug

#376 feat(alarm): add option to show keypad
  src/cards/alarm-control-panel-card/alarm-control-panel-card-config.ts
  src/cards/alarm-control-panel-card/alarm-control-panel-card-editor.ts
  src/cards/alarm-control-panel-card/alarm-control-panel-card.ts
  src/translations/de.json
  src/translations/el.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/it.json
  src/translations/nb.json
  src/translations/nl.json
  src/translations/pt-BR.json
  src/translations/sv.json
  src/translations/tr.json
  src/translations/zh-Hans.json
  src/translations/zh-Hant.json
Labels: enhancement

#353 Amend person card logic to allow for room presence
  .hass_dev/views/person-view.yaml
  src/cards/person-card/utils.ts
Labels: enhancement

#268 Entity picture option to chip entity card
  src/cards/chips-card/chips-card-editor.ts
  src/cards/chips-card/chips/entity-chip-editor.ts
  src/cards/chips-card/chips/entity-chip.ts
  src/utils/card-styles.ts
  src/utils/lovelace/chip/types.ts
Labels: enhancement

#393 Add entity picture support to entity card
  docs/cards/entity.md
  src/cards/chips-card/chips/entity-chip.ts
  src/cards/entity-card/entity-card-config.ts
  src/cards/entity-card/entity-card-editor.ts
  src/cards/entity-card/entity-card.ts
  src/shared/chip.ts
  src/utils/card-styles.ts
Labels: enhancement

#397 fix(person): align icon to center if no name and no state
  src/cards/person-card/person-card.ts
Labels: bug

#404 Improve chips list display in editor
  .gitignore
  src/cards/chips-card/chips-card-chips-editor.ts
  src/translations/de.json
  src/translations/el.json
  src/translations/en.json
  src/translations/fr.json
  src/translations/it.json
  src/translations/nb.json
  src/translations/nl.json
  src/translations/pt-BR.json
  src/translations/sv.json
  src/translations/tr.json
  src/translations/zh-Hans.json
  src/translations/zh-Hant.json
Labels: enhancement

#411 feat(theme): add disabled color in theme and color selector
  src/cards/alarm-control-panel-card/alarm-control-panel-card-editor.ts
  src/cards/alarm-control-panel-card/alarm-control-panel-card.ts
  src/cards/chips-card/chips-card-chips-editor.ts
  src/cards/chips-card/chips-card-editor.ts
  src/cards/chips-card/chips-card.ts
  src/cards/cover-card/cover-card-editor.ts
  src/cards/cover-card/cover-card.ts
  src/cards/entity-card/entity-card-editor.ts
  src/cards/entity-card/entity-card.ts
  src/cards/fan-card/fan-card-editor.ts
  src/cards/fan-card/fan-card.ts
  src/cards/light-card/light-card-editor.ts
  src/cards/light-card/light-card.ts
  src/cards/lock-card/lock-card-editor.ts
  src/cards/lock-card/lock-card.ts
  src/cards/media-player-card/media-player-card-editor.ts
  src/cards/media-player-card/media-player-card.ts
  src/cards/person-card/person-card-editor.ts
  src/cards/person-card/person-card.ts
  src/cards/template-card/template-card-editor.ts
  src/cards/template-card/template-card.ts
  src/cards/title-card/title-card-editor.ts
  src/cards/title-card/title-card.ts
  src/cards/update-card/update-card-editor.ts
  src/cards/update-card/update-card.ts
  src/cards/vacuum-card/vacuum-card-editor.ts
  src/cards/vacuum-card/vacuum-card.ts
  src/shared/button.ts
  src/shared/shape-avatar.ts
  src/shared/shape-icon.ts
  src/shared/slider.ts
  src/utils/base-element.ts
  src/utils/card-styles.ts
  src/utils/colors.ts
  src/utils/editor-styles.ts
  src/utils/theme.ts
Labels: enhancement

#420 chore: update selector and ha form
  src/utils/form/ha-form.ts
  src/utils/form/ha-selector.ts
Labels: tech

#418 feat(controls): improve collapsible controls and add option to fill container
  .hass_dev/views/fan-view.yaml
  .hass_dev/views/light-view.yaml
  .hass_dev/views/media-player-view.yaml
  .hass_dev/views/update-view.yaml
  docs/cards/alarm.md
  docs/cards/cover.md
  docs/cards/entity.md
  docs/cards/fan.md
  docs/cards/light.md
  docs/cards/lock.md
  docs/cards/media-player.md
  docs/cards/person.md
  docs/cards/template.md
  docs/cards/update.md
  docs/cards/vacuum.md
  src/cards/alarm-control-panel-card/alarm-control-panel-card-config.ts
  src/cards/alarm-control-panel-card/alarm-control-panel-card-editor.ts
  src/cards/alarm-control-panel-card/alarm-control-panel-card.ts
  src/cards/cover-card/cover-card-config.ts
  src/cards/cover-card/cover-card-editor.ts
  src/cards/cover-card/cover-card.ts
  src/cards/entity-card/entity-card-config.ts
  src/cards/entity-card/entity-card-editor.ts
  src/cards/entity-card/entity-card.ts
  src/cards/fan-card/fan-card-config.ts
  src/cards/fan-card/fan-card-editor.ts
  src/cards/fan-card/fan-card.ts
  src/cards/light-card/light-card-config.ts
  src/cards/light-card/light-card-editor.ts
  src/cards/light-card/light-card.ts
  src/cards/lock-card/lock-card-config.ts
  src/cards/lock-card/lock-card-editor.ts
  src/cards/lock-card/lock-card.ts
  src/cards/media-player-card/media-player-card-config.ts
  src/cards/media-player-card/media-player-card-editor.ts
  src/cards/media-player-card/media-player-card.ts
  src/cards/person-card/person-card-config.ts
  src/cards/person-card/person-card-editor.ts
  src/cards/person-card/person-card.ts
  src/cards/template-card/template-card-config.ts
  src/cards/template-card/template-card-editor.ts
  src/cards/template-card/template-card.ts
  src/cards/update-card/update-card-config.ts
  src/cards/update-card/update-card-editor.ts
  src/cards/update-card/update-card.ts
  src/cards/vacuum-card/vacuum-card-config.ts
  src/cards/vacuum-card/vacuum-card-editor.ts
  src/cards/vacuum-card/vacuum-card.ts
  src/translations/de.json
  src/translations/en.json
  src/translations/fr.json
  src/utils/card-styles.ts
  src/utils/form/fields.ts
  src/utils/layout.ts
  src/utils/theme.ts
Labels: enhancement
