Repository piitaya/lovelace-mushroom, pull requests merged in 2022-06, with the labels that each got.

#555 Feat: Badge to template card
  docs/cards/template.md
  src/cards/template-card/template-card-config.ts
  src/cards/template-card/template-card-editor.ts
  src/cards/template-card/template-card.ts
  src/translations/en.json
  src/translations/fr.json
Labels: enhancement

#561 Update zh-Hant.json
  src/translations/zh-Hant.json
Labels: translations

#569 feat(layout): better support for layout
  src/shared/card.ts
  src/utils/layout.ts
Labels: enhancement

#570 feat(template): add picture to template
  .hass_dev/views/template-view.yaml
  docs/cards/template.md
  src/cards/template-card/template-card-config.ts
  src/cards/template-card/template-card-editor.ts
  src/cards/template-card/template-card.ts
  src/translations/en.json
  src/translations/fr.json
Labels: enhancement

#573 refactor(entity): use base card in entity card
  src/cards/entity-card/entity-card.ts
Labels: tech
