Repository piitaya/lovelace-mushroom, pull requests merged in 2022-07, with the labels that each got.

#572 Update to Italian translation
  src/translations/it.json
Labels: translations

#575 feat(climate): create climate card
  .hass_dev/packages/climate.yaml
  README.md
  docs/cards/climate.md
  docs/images/climate-dark.png
  docs/images/climate-light.png
  src/cards/climate-card/climate-card-config.ts
  src/cards/climate-card/climate-card-editor.ts
  src/cards/climate-card/climate-card.ts
  src/cards/climate-card/const.ts
  src/cards/climate-card/controls/climate-hvac-modes-control.ts
  src/cards/climate-card/controls/climate-temperature-control.ts
  src/cards/climate-card/utils.ts
  src/cards/fan-card/controls/fan-oscillate-control.ts
  src/ha/common/number/clamp.ts
  src/ha/index.ts
  src/mushroom.ts
  src/shared/input-number.ts
  src/translations/en.json
  src/translations/fr.json
  src/utils/theme.ts
Labels: enhancement

#625 Update German translation
  src/translations/de.json
Labels: translations

#630 Clarify installation with HACS
  README.md
Labels: documentation

#643 fix(climate): improve theme support for input number
  src/shared/input-number.ts
Labels: bug

#644 feat(climate): add badge for idle action
  src/cards/climate-card/climate-card.ts
  src/cards/climate-card/utils.ts
  src/utils/theme.ts
Labels: enhancement

#645 feat(climate): change fan only mode color to teal by default
  src/utils/theme.ts
Labels: enhancement

#648 fix(template): use disabled color as default color for template card
  src/cards/template-card/template-card.ts
Labels: bug
