Repository piitaya/lovelace-mushroom, pull requests merged in 2023-06, with the labels that each got.

#1159 Spelling and rephrasing correction
  src/translations/he.json
Labels: translations

#1167 Use ha-card for title card
  src/cards/title-card/title-card.ts
Labels: bug

#1169 Add primary and accent color
  src/utils/colors.ts
Labels: enhancement

#1171 Add support for weather icon in template card and template chip
  docs/cards/chips.md
  docs/cards/template.md
  src/cards/chips-card/chips/template-chip.ts
  src/cards/template-card/template-card.ts
  src/utils/icons/weather-icon.ts
Labels: enhancement

#1174 Clean config
  .hass_dev/packages/demo.yaml
  .hass_dev/packages/number.yaml
Labels: tech

#1176 Add prefix to weather icon
  docs/cards/chips.md
  docs/cards/template.md
  src/cards/chips-card/chips/template-chip.ts
  src/cards/template-card/template-card.ts
  src/utils/icons/weather-icon.ts
Labels: enhancement

#1141 Use ha icons
  src/cards/alarm-control-panel-card/alarm-control-panel-card-editor.ts
  src/cards/alarm-control-panel-card/alarm-control-panel-card.ts
  src/cards/chips-card/chips/action-chip-editor.ts
  src/cards/chips-card/chips/action-chip.ts
  src/cards/chips-card/chips/alarm-control-panel-chip-editor.ts
  src/cards/chips-card/chips/alarm-control-panel-chip.ts
  src/cards/chips-card/chips/back-chip-editor.ts
  src/cards/chips-card/chips/back-chip.ts
  src/cards/chips-card/chips/entity-chip-editor.ts
  src/cards/chips-card/chips/entity-chip.ts
  src/cards/chips-card/chips/light-chip-editor.ts
  src/cards/chips-card/chips/light-chip.ts
  src/cards/chips-card/chips/menu-chip-editor.ts
  src/cards/chips-card/chips/menu-chip.ts
  src/cards/chips-card/chips/template-chip-editor.ts
  src/cards/chips-card/chips/template-chip.ts
  src/cards/chips-card/chips/weather-chip-editor.ts
  src/cards/climate-card/climate-card-editor.ts
  src/cards/climate-card/climate-card.ts
  src/cards/cover-card/cover-card-editor.ts
  src/cards/cover-card/cover-card.ts
  src/cards/entity-card/entity-card-editor.ts
  src/cards/entity-card/entity-card.ts
  src/cards/fan-card/fan-card-editor.ts
  src/cards/fan-card/fan-card.ts
  src/cards/humidifier-card/humidifier-card-editor.ts
  src/cards/humidifier-card/humidifier-card.ts
  src/cards/light-card/light-card-editor.ts
  src/cards/light-card/light-card.ts
  src/cards/lock-card/lock-card-editor.ts
  src/cards/lock-card/lock-card.ts
  src/cards/media-player-card/media-player-card-editor.ts
  src/cards/media-player-card/utils.ts
  src/cards/number-card/number-card-editor.ts
  src/cards/number-card/number-card.ts
  src/cards/person-card/person-card-editor.ts
  src/cards/person-card/person-card.ts
  src/cards/select-card/select-card-editor.ts
  src/cards/select-card/select-card.ts
  src/cards/template-card/template-card-editor.ts
  src/cards/template-card/template-card.ts
  src/cards/title-card/title-card-editor.ts
  src/cards/update-card/update-card-editor.ts
  src/cards/update-card/update-card.ts
  src/cards/vacuum-card/vacuum-card-editor.ts
  src/cards/vacuum-card/vacuum-card.ts
  src/shared/chip.ts
  src/shared/shape-icon.ts
  src/utils/base-card.ts
  src/utils/base-element.ts
  src/utils/icons/alarm-panel-icon.ts
  src/utils/icons/binary-sensor-icon.ts
  src/utils/icons/cover-icon.ts
  src/utils/icons/domain-icon.ts
  src/utils/icons/sensor-icon.ts
  src/utils/icons/state-icon.ts
  src/utils/icons/weather-icon.ts
Labels: enhancement

#1173 Add assist action and built-in hass-action
  hacs.json
  src/cards/alarm-control-panel-card/alarm-control-panel-card-editor.ts
  src/cards/chips-card/chips/action-chip-editor.ts
  src/cards/chips-card/chips/alarm-control-panel-chip-editor.ts
  src/cards/chips-card/chips/weather-chip-editor.ts
  src/cards/climate-card/climate-card-editor.ts
  src/cards/person-card/person-card-editor.ts
  src/cards/select-card/select-card-editor.ts
  src/cards/update-card/update-card-editor.ts
  src/ha/common/entity/compute-state-display.ts
  src/ha/common/navigate.ts
  src/ha/data/haptics.ts
  src/ha/data/integration.ts
  src/ha/data/lovelace.ts
  src/ha/index.ts
  src/ha/panels/lovelace/common/entity/toggle-entity.ts
  src/ha/panels/lovelace/common/handle-actions.ts
  src/ha/panels/lovelace/editor/structs/action-struct.ts
  src/shared/config/actions-config.ts
Labels: enhancement

#1175 Use timezone settings to format state and date
  src/cards/chips-card/chips/alarm-control-panel-chip.ts
  src/cards/chips-card/chips/entity-chip.ts
  src/cards/chips-card/chips/light-chip.ts
  src/cards/chips-card/chips/weather-chip.ts
  src/cards/climate-card/climate-card.ts
  src/cards/cover-card/cover-card.ts
  src/cards/fan-card/fan-card.ts
  src/cards/humidifier-card/humidifier-card.ts
  src/cards/light-card/light-card.ts
  src/cards/light-card/utils.ts
  src/cards/media-player-card/utils.ts
  src/cards/number-card/number-card.ts
  src/cards/select-card/controls/select-option-control.ts
  src/ha/common/datetime/duration.ts
  src/ha/common/datetime/format_date.ts
  src/ha/common/datetime/format_date_time.ts
  src/ha/common/datetime/format_time.ts
  src/ha/common/datetime/milliseconds_to_duration.ts
  src/ha/common/datetime/seconds_to_duration.ts
  src/ha/common/entity/compute_domain.ts
  src/ha/common/entity/compute_object_id.ts
  src/ha/common/entity/compute_state_display.ts
  src/ha/common/entity/compute_state_domain.ts
  src/ha/common/entity/compute_state_name.ts
  src/ha/data/entity.ts
  src/ha/data/entity_registry.ts
  src/ha/data/light.ts
  src/ha/data/translation.ts
  src/ha/data/update.ts
  src/ha/index.ts
  src/ha/panels/lovelace/common/entity/turn-on-off-entities.ts
  src/ha/panels/lovelace/common/entity/turn-on-off-entity.ts
  src/utils/base-card.ts
  tsconfig.json
Labels: enhancement
