Repository piitaya/lovelace-mushroom, pull requests merged in 2023-04, with the labels that each got.

#1093 Fix action handler
  src/ha/panels/lovelace/common/directives/action-handler-directive.ts
Labels: bug

#1111 Force template conversion to string
  src/cards/chips-card/chips/template-chip.ts
  src/cards/template-card/template-card.ts
  src/cards/title-card/title-card.ts
Labels: bug

#1112 Refactor spacer chip
  src/cards/chips-card/chips-card-chips-editor.ts
  src/translations/fr.json
Labels: tech

#1117 Update it.json
  src/translations/it.json
Labels: translations

#1127 Use translations for select options
  src/cards/select-card/controls/select-option-control.ts
Labels: bug

#1119 Refactor selector naming
  src/cards/chips-card/chips/action-chip-editor.ts
  src/cards/chips-card/chips/alarm-control-panel-chip-editor.ts
  src/cards/chips-card/chips/entity-chip-editor.ts
  src/cards/chips-card/chips/light-chip-editor.ts
  src/cards/entity-card/entity-card-editor.ts
  src/cards/light-card/light-card-editor.ts
  src/cards/number-card/number-card-editor.ts
  src/cards/select-card/select-card-editor.ts
  src/cards/template-card/template-card-editor.ts
  src/cards/title-card/title-card-editor.ts
  src/shared/config/appearance-config.ts
  src/utils/form/custom/ha-selector-mushroom-alignment.ts
  src/utils/form/custom/ha-selector-mushroom-color.ts
  src/utils/form/custom/ha-selector-mushroom-icon-type.ts
  src/utils/form/custom/ha-selector-mushroom-info.ts
  src/utils/form/custom/ha-selector-mushroom-layout.ts
Labels: tech

#1129 Sync icon and state display with HA 2023.5
  src/ha/common/entity/compute-state-display.ts
  src/utils/icons/domain-icon.ts
Labels: enhancement
