Repository piitaya/lovelace-mushroom, pull requests merged in 2023-01, with the labels that each got.

#931 Update state icons
  src/utils/icons/binary-sensor-icon.ts
  src/utils/icons/cover-icon.ts
  src/utils/icons/domain-icon.ts
  src/utils/icons/sensor-icon.ts
  src/utils/icons/weather-icon.ts
Labels: bug

#929 Ha 2022 11 clean backward compat
  src/cards/alarm-control-panel-card/alarm-control-panel-card-editor.ts
  src/cards/chips-card/chips-card-editor.ts
  src/cards/chips-card/chips/action-chip-editor.ts
  src/cards/chips-card/chips/alarm-control-panel-chip-editor.ts
  src/cards/chips-card/chips/entity-chip-editor.ts
  src/cards/chips-card/chips/light-chip-editor.ts
  src/cards/chips-card/chips/template-chip-editor.ts
  src/cards/chips-card/chips/weather-chip-editor.ts
  src/cards/climate-card/climate-card-editor.ts
  src/cards/cover-card/cover-card-editor.ts
  src/cards/entity-card/entity-card-editor.ts
  src/cards/fan-card/fan-card-editor.ts
  src/cards/humidifier-card/humidifier-card-editor.ts
  src/cards/light-card/light-card-editor.ts
  src/cards/lock-card/lock-card-editor.ts
  src/cards/media-player-card/media-player-card-editor.ts
  src/cards/person-card/person-card-editor.ts
  src/cards/template-card/template-card-editor.ts
  src/cards/title-card/title-card-editor.ts
  src/cards/update-card/update-card-editor.ts
  src/cards/vacuum-card/vacuum-card-editor.ts
  src/localize.ts
  src/mushroom.ts
  src/shared/config/actions-config.ts
  src/shared/editor/action-picker.ts
  src/utils/form/custom/ha-selector-mushroom-action.ts
  src/utils/form/ha-selector.ts
  src/utils/loader.ts
Labels: tech

#940 Update dependencies
  package-lock.json
  package.json
  rollup.config.mjs
Labels: tech

#941 Select card fixes
  .hass_dev/lovelace-mushroom-showcase.yaml
  .hass_dev/packages/select.yaml
  .hass_dev/views/select-view.yaml
  src/cards/select-card/select-card-editor.ts
Labels: bug

#952 Add navigate and url action to title and subtitle
  .hass_dev/views/title-view.yaml
  docs/cards/title.md
  src/cards/title-card/title-card-config.ts
  src/cards/title-card/title-card-editor.ts
  src/cards/title-card/title-card.ts
Labels: enhancement

#953 Add translations and rtl support to title actions
  src/cards/title-card/title-card.ts
  src/translations/en.json
  src/translations/fr.json
Labels: bug

#972 Improve old browser support
  .babelrc
  package-lock.json
  package.json
  rollup.config.mjs
Labels: bug

#949 Added Catalan translations
  src/localize.ts
  src/translations/ca.json
Labels: translations

#968 feat(translation): add korean translation
  src/localize.ts
  src/translations/ko-KR.json
Labels: translations
