Repository piitaya/lovelace-mushroom, pull requests merged in 2023-02, with the labels that each got.

#997 several small syntax typos
  docs/cards/update.md
Labels: documentation

#996 small syntax typos
  docs/cards/template.md
Labels: documentation

#995 small syntax typo
  docs/cards/select.md
Labels: documentation

#994 several edits
  docs/cards/person.md
Labels: documentation

#993 small syntax typo
  docs/cards/media-player.md
Labels: documentation

#992 small syntax typo
  docs/cards/lock.md
Labels: documentation

#990 small syntax typo
  docs/cards/humidifier.md
Labels: documentation

#991 small syntax typo
  docs/cards/light.md
Labels: documentation

#988 small syntax typo
  docs/cards/fan.md
Labels: documentation

#986 small syntax typo
  docs/cards/climate.md
Labels: documentation

#1019 Add mushroom ressource to config
  .hass_dev/configuration.yaml
  README.md
Labels: tech

#1037 Display precision support
  src/cards/cover-card/cover-card.ts
  src/cards/fan-card/fan-card.ts
  src/cards/humidifier-card/humidifier-card.ts
  src/cards/light-card/light-card.ts
  src/cards/media-player-card/media-player-card.ts
  src/ha/common/const.ts
  src/ha/common/datetime/duration.ts
  src/ha/common/datetime/seconds_to_duration.ts
  src/ha/common/entity/compute-state-display.ts
  src/ha/common/entity/supports-feature.ts
  src/ha/common/number/format_number.ts
  src/ha/common/string/compare.ts
  src/ha/common/translations/blank_before_percent.ts
  src/ha/data/update.ts
  src/ha/types.ts
Labels: bug

#1038 Improve buttons layout
  src/cards/climate-card/climate-card.ts
  src/cards/update-card/update-card.ts
  src/shared/button-group.ts
Labels: bug

#1039 Fix documentation URL
  src/utils/custom-cards.ts
Labels: bug

#1043 Update German translation
  src/translations/de.json
Labels: translations

#1046 Fix climate temperature buttons in horizontal layout
  .hass_dev/views/humidifier-view.yaml
  .hass_dev/views/vacuum-view.yaml
  src/shared/button-group.ts
  src/shared/input-number.ts
Labels: bug
