Repository piitaya/lovelace-mushroom, pull requests merged in 2024-08, with the labels that each got.

#1488 Add 2024.7 backward compatibility
  package.json
  src/cards/alarm-control-panel-card/alarm-control-panel-card-editor.ts
  src/cards/chips-card/chips/action-chip-editor.ts
  src/cards/chips-card/chips/alarm-control-panel-chip-editor.ts
  src/cards/chips-card/chips/weather-chip-editor.ts
  src/cards/person-card/person-card-editor.ts
  src/cards/select-card/select-card-editor.ts
  src/cards/update-card/update-card-editor.ts
  src/shared/config/actions-config.ts
  src/utils/base-element.ts
Labels: bug

#1497 Use dynamic row height when using collapsible controls
  docs/cards/climate.md
  docs/cards/fan.md
  docs/cards/humidifier.md
  docs/cards/light.md
  docs/cards/media-player.md
  docs/cards/update.md
  src/utils/base-card.ts
Labels: bug

#1498 Improve default size in sections
  src/shared/card.ts
  src/utils/base-card.ts
Labels: bug

#1501 Add missing box shadow theme variable to entity badge
  src/badges/template/template-badge.ts
Labels: bug

#1506 fix markdown table in docs
  docs/cards/fan.md
  docs/cards/humidifier.md
  docs/cards/light.md
  docs/cards/media-player.md
  docs/cards/update.md
Labels: documentation

#1504 SV translation to more cards
  src/translations/sv.json
Labels: translations

#1508 Fix typos and add missing translations for Danish
  src/translations/da.json
Labels: translations

#1519 Allow to change badge size and border radius
  src/badges/template/template-badge.ts
Labels: enhancement
