Repository piitaya/lovelace-mushroom, pull requests merged in 2025-03, with the labels that each got.

#1666 Revert color lib bump
  package-lock.json
  package.json
  src/cards/light-card/controls/light-color-control.ts
  src/cards/light-card/utils.ts
  src/utils/colors.ts
Labels: bug

#1663 Translations update from Hosted Weblate
  src/translations/it.json
Labels: translations

#1647 Add fan direction button to fan card
  .hass_dev/views/fan-view.yaml
  docs/cards/fan.md
  src/cards/fan-card/controls/fan-direction-control.ts
  src/cards/fan-card/fan-card-config.ts
  src/cards/fan-card/fan-card-editor.ts
  src/cards/fan-card/fan-card.ts
  src/translations/en.json
Labels: enhancement

#1674 Translations update from Hosted Weblate
  src/translations/ar.json
  src/translations/pl.json
Labels: translations

#1670 Add empty card
  docs/cards/empty.md
  src/cards/empty-card/const.ts
  src/cards/empty-card/empty-card-config.ts
  src/cards/empty-card/empty-card-editor.ts
  src/cards/empty-card/empty-card.ts
  src/mushroom.ts
  src/translations/de.json
  src/translations/en.json
Labels: enhancement
